### PR TITLE
Add OpAtomic_Inc-Dec-Min-Max

### PR DESCRIPTION
**Pull request by DanielSvoboda**
add these:

-  OpAtomicInc
-  OpAtomicDec
-  OpAtomicMin
-  OpAtomicMax

 
 my visual studio also changed the formatting...

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
Those look duplicate (the functions already exist)

**Comment by DanielSvoboda** [comment]
I removed the duplicates

**Comment by raphaelthegreat** [comment]
The OpAtomicMin/OpAtomicMax functions you added emit OpAtomicSMin/OpAtomicSMax which are already present so also duplicates. OpAtomicInc/OpAtomicDec also emit OpAtomicIIncrement/OpAtomicIDecrement which also exist. When adding functions to sirit you have to keep the original name of the function as it should closely match with spirv spec which we use for reference

**Comment by DanielSvoboda** [comment]
I didn't notice their existence, I had done it at dawn

**Pull request closed without merging**
